export const genres = [
  { label: 'Все', value: '' },
  { label: 'Аниме', value: 'аниме' },
  { label: 'Биография', value: 'биография' },
  { label: 'Боевик', value: 'боевик' },
  { label: 'Вестерн', value: 'вестерн' },
  { label: 'Военный', value: 'военный' },
  { label: 'Детектив', value: 'детектив' },
  { label: 'Детский', value: 'детский' },
  { label: 'Для взрослых', value: 'для взрослых' },
  { label: 'Документальный', value: 'документальный' },
  { label: 'Драма', value: 'драма' },
  { label: 'Игра', value: 'игра' },
  { label: 'История', value: 'история' },
  { label: 'Комедия', value: 'комедия' },
  { label: 'Концерт', value: 'концерт' },
  { label: 'Короткометражка', value: 'короткометражка' },
  { label: 'Криминал', value: 'криминал' },
  { label: 'Мелодрама', value: 'мелодрама' },
  { label: 'Музыка', value: 'музыка' },
  { label: 'Мультфильм', value: 'мультфильм' },
  { label: 'Мюзикл', value: 'мюзикл' },
  { label: 'Новости', value: 'новости' },
  { label: 'Приключения', value: 'приключения' },
  { label: 'Реальное ТВ', value: 'реальное тв' },
  { label: 'Семейный', value: 'семейный' },
  { label: 'Спорт', value: 'спорт' },
  { label: 'Ток-шоу', value: 'ток-шоу' },
  { label: 'Триллер', value: 'триллер' },
  { label: 'Ужасы', value: 'ужасы' },
  { label: 'Фантастика', value: 'фантастика' },
  { label: 'Фильм-нуар', value: 'фильм-нуар' },
  { label: 'Фэнтези', value: 'фэнтези' },
  { label: 'Церемония', value: 'церемония' },
];

export const ratings = [
  { label: 'Любой рейтинг', value: '' },
  { label: 'От 9 и выше', value: '9-10' },
  { label: 'От 8 и выше', value: '8-10' },
  { label: 'От 7 и выше', value: '7-10' },
  { label: 'От 6 и выше', value: '6-10' },
  { label: 'От 5 и выше', value: '5-10' },
];

export const sorting = [
  { label: 'Рекомендуемые', value: '' },
  { label: 'По рейтингу', value: 'rating.kp' },
  { label: 'По дате выхода', value: 'releaseYears.start' },
];

export const years = [
  { label: 'Все годы', value: '' },
  { label: '2025', value: '2025' },
  { label: '2024', value: '2024' },
  { label: '2023', value: '2023' },
  { label: '2022', value: '2022' },
  { label: '2021', value: '2021' },
  { label: '2020', value: '2020' },
  { label: '2010-2019', value: '2010-2019' },
  { label: '2000-2009', value: '2000-2009' },
  { label: '1990-1999', value: '1990-1999' },
  { label: '1980-1989', value: '1980-1989' },
  { label: 'до 1980', value: '1900-1979' },
];
